[package]
name = "async_singleflight"
version = "0.1.0"
authors = ["Pure White <wudi.daniel@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
